sudo: false
# need to declare the language as well as the matrix below
language: node_js
# having top-level `env:` adds a phantom build
# https://github.com/travis-ci/travis-ci/issues/4681
#env: DEPLOY_VERSION=testing
matrix:
  include:
    # LTS is our most important target
    - node_js: "6"
      # DEPLOY_VERSION is used to set the couchapp setup mode for test/tap/registry.js
      # only gather coverage info for LTS
      env: DEPLOY_VERSION=testing COVERALLS_REPO_TOKEN="$COVERALLS_OPTIONAL_TOKEN"
      script:
        - "node . run tap-cover -- \"test/tap/*.js\""
        - "unset COVERALLS_REPO_TOKEN ; node . run tap -- \"test/slow/*.js\" \"test/broken-under-*/*.js\""

before_install:
  # required by test/tap/registry.js
  - "mkdir -p /var/run/couchdb"